services:
  mongo:
    image: mongo
    container_name: con-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asdf
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s


  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-cluster cluster-id --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s



  cache:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s


  app:
    build: ./app
    container_name: app
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy
      cache:
        condition: service_healthy

    ports:
      - "8000:8000"
    environment:
      PIZZA_MONGO_USER: root
      PIZZA_MONGO_PASS: asdf
      PIZZA_MONGO_HOST: mongo
      PIZZA_MONGO_PORT: 27017
      PIZZA_HOST_PORT_KAFKA: kafka:29092
      PIZZA_REDIS_HOST: cache
      PIZZA_REDIS_PORT: 6379

  preprocessor:
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy

    build: ./preprocessor
    container_name: preprocessor
    environment:
      PIZZA_HOST_PORT_KAFKA: kafka:29092
      PYTHONUNBUFFERED: 1


#
#  kitchen_worker:
#    build: ./kitchen_worker
#    depends_on:
#      kafka:
#        condition: service_healthy
#      mongo:
#        condition: service_healthy
#      cache:
#        condition: service_healthy
#
#    container_name: kitchen_worker
#    environment:
#      PIZZA_MONGO_USER: root
#      PIZZA_MONGO_PASS: asdf
#      PIZZA_MONGO_HOST: mongo
#      PIZZA_MONGO_PORT: 27017
#      PIZZA_HOST_PORT_KAFKA: kafka:29092
#      PIZZA_REDIS_HOST: cache
#      PIZZA_REDIS_PORT: 6379
#      PYTHONUNBUFFERED: 1
#
#  text_worker:
#    build: ./text_worker
#    depends_on:
#      kafka:
#        condition: service_healthy
#      mongo:
#        condition: service_healthy
#      cache:
#        condition: service_healthy
#
#    container_name: text_worker
#    environment:
#      PIZZA_MONGO_USER: root
#      PIZZA_MONGO_PASS: asdf
#      PIZZA_MONGO_HOST: mongo
#      PIZZA_MONGO_PORT: 27017
#      PIZZA_HOST_PORT_KAFKA: kafka:29092
#      PYTHONUNBUFFERED: 1
#


volumes:
  kafka_data:
  cache:



